### ISSUE TITLE
[PE-D] Medical History truncated to "..." when involvement is long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-3/tp#215]
![image.png](https://raw.githubusercontent.com/neojxuan/ped/main/files/7e851172-4eb7-4631-9923-d07ac43943c4.png)

The "..." is not useful and could be potentially misleading if teachers assume the student does not have medical history. If the purple tag is not meant to display the history perhaps it can be replaced with an icon or an exclamation mark and users will have to open the medical window to access the history.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: neojxuan/ped#3

**Comment by random689** [comment]
Done and fixed
