### ISSUE TITLE
[PE-D] Cannot edit teacher details of a teacher not present in filtered results panel

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-3/tp#222]
Reproduce:

```
filterTeacher woiencoirnvowierniwrj
editTeacher 2 n/Ben Tenison
```

This command will filter out no one because the given predicate is gibberish. But, when you try to edit the teacher details of a teacher originally at `INDEX = 2`, it says the teacher index does not exist

![image.png](https://raw.githubusercontent.com/rish-16/ped/main/files/5f0535bb-4b2b-468e-81d3-6d890feebc18.png)

However, my teacher list has 3 teachers:

![image.png](https://raw.githubusercontent.com/rish-16/ped/main/files/8019b74f-71a4-4b42-b55a-3569227b2536.png)

> Ideally, all teacher-related edit and modification commands must work on the raw records, not just the filtered list.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: rish-16/ped#7

**Comment by random689** [comment]
Rejected cause this is the intended function
