### ISSUE TITLE
[PE-D] Suggestion to standardise class naming

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-3/tp#225]
## Suggestions on aesthetics 

Since classes are seldom differentiated by their casing in my experience, maybe it is possible to standardise all to for example upper case? Example: 3a2 -> 3A2

![image.png](https://raw.githubusercontent.com/Droffilc13/ped/main/files/f6bf8f15-ab2c-4451-8a67-a3524b28c4b6.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Droffilc13/ped#3

**Comment by junghon3709** [comment]
Make class case insensitive 3a1 -> 3A1

**Comment by cliveong** [comment]
Not allowed to fix, closed
