### ISSUE TITLE
[PE-D] Constraints on FORM_CLASS are too strict

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-3/tp#227]
Schools may adopt different ways of naming classes. Classes should not be limited to being names with |LEVEL|STRING|[ALPHANUMERIC]| as many schools have classes that are purely made up of numbers (eg. 210) to represent a class in secondary 2.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: neojxuan/ped#7

**Comment by junghon3709** [comment]
Make it of the form LEVEL [STRING]

**Comment by g4ryy** [comment]
We will acknowledge this as a feature flaw. I have added this to the user guide so I shall close this issue,
