### ISSUE TITLE
[PE-D] Typo in involvement definition

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T16-3/tp#232]
This is [missing "a"] broad term describing why the user would even want to bother storing the student in the ad...

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: neojxuan/ped#9

**Comment by junghon3709** [comment]
![image](https://user-images.githubusercontent.com/50390582/139662723-22a3e5f3-862f-4a10-a52c-abb87d3be27d.png)
