### ISSUE TITLE
Undo command needs to execute multiple times for editing medical history

### ISSUE THREAD

**Issue by junghon3709** [AY2122S1-CS2103-T16-3/tp#248]
For example, a user can execute `medical 1 m/ADHD`. If the user does this multiple times, the address books treats it as a new action despite there being no outstanding change. This means that `undo` command needs to be executed multiple times before users can return back to the previous state, which is obviously not ideal.

**Comment by g4ryy** [comment]
I shall close this issue since it has been fixed
