### ISSUE TITLE
Parameters that take in any values

### ISSUE THREAD

**Issue by g4ryy** [AY2122S1-CS2103-T16-3/tp#252]
Need to warn users that if their text starts with any NewAddressBook prefix, they cannot have space after the prefix for that parameter.

e.g. editStudent i/e/hello works but not editStudent i/ e/hello as the e/hello part will be treated as an email field and the involvement will be treated as blank.

Applies to involvement, address, title, venue

**Comment by junghon3709** [comment]
![image](https://user-images.githubusercontent.com/50390582/140372948-75512042-ba1d-42d3-84af-9a24e0a2825f.png)

I have added this under my latest PR. Is this what you mean to say?
