### ISSUE TITLE
This needs to be made clearer, I think

### ISSUE THREAD

**Issue by junghon3709** [AY2122S1-CS2103-T16-3/tp#259]
![image](https://user-images.githubusercontent.com/50390582/140461364-b6d94de1-5522-47ff-85f2-aaf583a74ad9.png)

**Comment by cliveong** [comment]
Which part is unclear

**Comment by junghon3709** [comment]
I don't understand what you mean by `Adapts find command` and `Update model itself`? It's kinda vague

**Comment by cliveong** [comment]
kk
