### ISSUE TITLE
Make medical history window say "no medical history" if the student has no medical history

### ISSUE THREAD

**Issue by junghon3709** [AY2122S1-CS2103-T16-3/tp#260]
![image](https://user-images.githubusercontent.com/50390582/140467076-eb9a0cad-78ae-401a-bb07-2df5fec14893.png)

Instead of leaving it empty, which is confusing to the user.

(if this is fixed, need to edit the mss also).

**Comment by cliveong** [comment]
Isnt this considered an additional feature as the userguide does not have "no medical history" will be shown if the student has no medical history

**Comment by junghon3709** [comment]
I dunno, I think it's something that can be potentially held against us.

**Comment by cliveong** [comment]
Ya but now is feature freeze, at most can add into ug iirc

**Comment by junghon3709** [comment]
Honestly you're right, I've looked into this conversation, and it seems like the feature freeze is more annoying than I thought:
https://github.com/nus-cs2103-AY2122S1/forum/issues/362

So I think I'll just close this and mention it in the UG
